# Generated by Django 2.0.2 on 2018-03-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Pizza',
                'verbose_name_plural': 'Pizzas',
            },
        ),
        migrations.CreateModel(
            name='PizzaSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveSmallIntegerField(help_text='in centimeter(cm)', unique=True)),
            ],
            options={
                'verbose_name': 'Pizza Size',
                'verbose_name_plural': 'Pizza Sizes',
                'ordering': ['size'],
            },
        ),
        migrations.AddField(
            model_name='pizza',
            name='sizes',
            field=models.ManyToManyField(related_name='pizzas', to='product.PizzaSize'),
        ),
    ]
