# Generated by Django 2.0.2 on 2018-03-05 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='sizes',
        ),
    ]
